<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Promise polyfill</title>

</head>
<body>

    <h1>
        <a href="https://github.com/Octane/Promise/" title="Go to GitHub">
            Promise polyfill
        </a>
    </h1>

    <script>
        try {
            console.log;
        }
        catch (error) {
            window.console = {
                log: function () {
                    var pre = document.createElement('pre');
                    pre.appendChild(document.createTextNode(
                        Array.prototype.join.call(arguments, ', ')
                    ));
                    document.body.appendChild(pre);
                }
            };
        }
    </script>

    <!--[if IE 8]>
    <script>
        if (!Array.prototype.forEach) {
            Array.prototype.forEach = function (func, boundThis) {
                var length = this.length,
                    i = 0;
                while (i < length) {
                    if (i in this) {
                        func.call(boundThis, this[i], i, this);
                    }
                    i++;
                }
            };
        }
        if (!Array.prototype.every) {
            Array.prototype.every = function (func, boundThis) {
                var length = this.length,
                    i = 0;
                while (i < length) {
                    if (i in this && !func.call(boundThis, this[i], i, this)) {
                        return false;
                    }
                    i++;
                }
                return true;
            };
        }
    </script>
    <script src="setimmediate/setimmediate-ie8.js"></script>
    <![endif]-->

    <script src="setimmediate/setimmediate.js"></script>
    <script src="promise.js"></script>
    <script>

        function test(desc, tester) {
            return new Promise(function (resolve, reject) {
                var settled = false;
                tester(function (result) {
                    settled = true;
                    if (result) {
                        resolve(desc);
                    } else {
                        reject(new Error(desc));
                    }
                });
                setTimeout(function () {
                    if (!settled) {
                        reject(new Error(desc));
                    }
                }, 3000);
            });
        }

        Promise.all([

            test('call resolver sync', function (assert) {
                var x = 0,
                    p1 = new Promise(function () {
                        x = 1;
                    }),
                    p2 = new Promise(function () {
                        assert(x == 1);
                    });
            }),

            test('call resolver once', function (assert) {
                var callCount = 0;
                new Promise(function () {
                    assert(callCount == 0);
                    callCount++;
                }).then().then().then().then();
            }),

            test('fulfill async', function (assert) {
                var x = 0;
                new Promise(function (resolve) {
                    resolve();
                }).then(function () {
                    x = 1;
                });
                assert(x == 0);
            }),

            test('reject async', function (assert) {
                var x = 0;
                new Promise(function (resolve, reject) {
                    reject();
                })['catch'](function () {
                    x = 1;
                });
                assert(x == 0);
            }),

            test('reject resolver error', function (assert) {
                new Promise(function (resolve, reject) {
                    throw Error('resolver error');
                }).then(function () {
                    assert(false);
                }, function (reason) {
                    assert(true);
                });
            }),

            test('no reject resolver error', function (assert) {
                new Promise(function (resolve, reject) {
                    resolve();
                    throw new Error('resolver error');
                }).then(function () {
                    assert(true);
                }, function (reason) {
                    assert(false);
                });
            }),

            test('call something one (resolve first)', function (assert) {
                new Promise(function (resolve, reject) {
                    resolve();
                    reject();
                    resolve();
                    reject();
                }).then(function () {
                    assert(true);
                }, function (reason) {
                    assert(false);
                });
            }),

            test('call something one (reject first)', function (assert) {
                new Promise(function (resolve, reject) {
                    reject();
                    resolve();
                    reject();
                    resolve();
                }).then(function () {
                    assert(false);
                }, function (reason) {
                    assert(true);
                });
            }),

            test('fulfill once', function (assert) {
                var callCount = 0;
                new Promise(function (resolve) {
                    resolve();
                    resolve();
                    resolve();
                }).then(function () {
                    assert(callCount == 0);
                    callCount++;
                });
            }),

            test('reject once', function (assert) {
                var callCount = 0;
                new Promise(function (resolve, reject) {
                    reject();
                    reject();
                    reject();
                })['catch'](function () {
                    assert(callCount == 0);
                    callCount++;
                });
            }),

            test('settled thenable', function (assert) {
                var success = false,
                    p = new Promise(function (resolve) {
                        resolve(5);
                    }).then(function (val) {
                        p.then(function (val) {
                            p.then(function (val) {
                                p.then(function (val) {
                                    success = val == 5;
                                });
                                return val;
                            });
                            return val;
                        });
                        return val;
                    });
                setTimeout(function () {
                    assert(success);
                }, 100);
            }),

            test('onFulfilled return promise', function (assert) {
                var success = false;
                new Promise(function (resolve) {
                    resolve();
                }).then(function () {
                    return new Promise(function (resolve) {
                        resolve();
                    });
                }).then(function () {
                    success = true;
                });
                setTimeout(function () {
                    assert(success);
                }, 100);
            }),

            test('onRejected return promise', function (assert) {
                var success = false;
                new Promise(function (resolve, reject) {
                    resolve();
                })['catch'](function () {
                    return new Promise(function (resolve) {
                        resolve();
                    });
                }).then(function () {
                    success = true;
                });
                setTimeout(function () {
                    assert(success);
                }, 200);
            }),

            test('return fulfilled promise', function (assert) {
                var p1 = Promise.resolve(1),
                    p2 = Promise.resolve(2),
                    success = false;
                p1.then(function () {
                    return p2;
                }).then(function (value) {
                    success = value == 2;
                });
                setTimeout(function () {
                    assert(success);
                }, 100);
            }),

            test('return rejected promise', function (assert) {
                var p1 = Promise.reject(1),
                    p2 = Promise.reject(2),
                    success = false;
                p1.then(function () {
                    return p2;
                })['catch'](function (reason) {
                    success = reason == 1;
                });
                setTimeout(function () {
                    assert(success);
                }, 100);
            }),

            test('return self', function (assert) {
                var success = false,
                    p = Promise.resolve(1);
                p.then(function () {
                    return p;
                }).then(function () {
                    success = true;
                });
                setTimeout(function () {
                    assert(success);
                }, 100);
            }),

            test('save initial value', function (assert) {
                var p = Promise.resolve(1);
                p.then(function () {
                    return 5;
                });
                p.then(function (value) {
                    assert(value == 1);
                })
            }),

            test('save initial reason', function (assert) {
                var initialReason = new Error('initial error'),
                    p = new Promise(function (resolve, reject) {
                        reject(initialReason);
                    });
                p['catch'](function (reason) {
                    throw Error('other error');
                });
                p['catch'](function (reason) {
                    assert(reason == initialReason);
                });
            }),

            test('transfer values', function (assert) {
                Promise.resolve(1).then(function (value) {
                    return value + 1;
                }).then(function (value) {
                    return value + 1;
                }).then(function (value) {
                    assert(value == 3);
                })
            }),

            test('transfer reasons', function (assert) {
                var initialReason = new Error('initial error');
                Promise.reject(initialReason)['catch'](function (reason) {
                    throw reason;
                })['catch'](function (reason) {
                    throw reason;
                })['catch'](function (reason) {
                    assert(reason == initialReason);
                });
            }),

            test('await resolve', function (assert) {
                new Promise(function (resolve) {
                    setTimeout(resolve, 100);
                }).then(function () {
                    assert(true);
                });
            }),

            test('await reject', function (assert) {
                new Promise(function (resolve, reject) {
                    setTimeout(reject, 100);
                })['catch'](function () {
                    assert(true);
                });
            }),

            test('onFulfilled error', function (assert) {
                Promise.resolve().then(function () {
                    throw new Error('test error');
                })['catch'](function () {
                    assert(true);
                });
            }),

            test('onRejected error', function (assert) {
                Promise.reject()['catch'](function () {
                    throw new Error('test error');
                })['catch'](function () {
                    assert(true);
                });
            }),

            test('race', function (assert) {
                var p1 = new Promise(function (resolve) {
                        setTimeout(function () {
                            resolve(1);
                        }, 150);
                    }),
                    p2 = new Promise(function (resolve) {
                        setTimeout(function () {
                            resolve(2);
                        }, 50);
                    }),
                    p3 = new Promise(function (resolve) {
                        setTimeout(function () {
                            resolve(3);
                        }, 100);
                    });
                Promise.race([p1, p2, p3]).then(function (value) {
                    assert(value == 2);
                });
            }),

            test('resolve(promise)', function (assert) {
                Promise.resolve(new Promise(function (resolve) {
                    resolve(1);
                })).then(function (value) {
                    assert(value == 1);
                });
            }),

            test('reject(promise)', function (assert) {
                var p = new Promise(function (resolve) {
                        resolve(1);
                    });
                Promise.reject(p)['catch'](function (value) {
                    assert(value == p);
                });
            }),

            //Chrome and Firefox work differently
            /*test('then(promise)', function (assert) {
                var p1 = new Promise(function (resolve) {
                        resolve();
                    }),
                    p2 = new Promise(function (resolve) {
                        resolve();
                    });

                p1.then(p2).then(function () {
                    assert(true); //Aurora 31
                }, function () {
                    assert(false); //Chrome 36
                });
            }),*/

            Promise.resolve(),

        ]).then(function () {
            console.log('All tests completed successfully.');
        }, function (reason) {
            console.log(reason.toString());
        });

    </script>

</body>
</html>
